name: my first workflow
on:
  push: 
jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4


      - name: print message
        run: echo "hello world , from first github aciton!"
